//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DragonCave
{
	public class DCMessages
	{
		public static string NewGame = "Welcome to Dragon Cave!\n"
			+ "Try to find the gold and return here to climb back out.\n"
				+ "You will have 1 arrow that you can shoot.\n"
				+ "Try the following commands:\n"
				+ "Move (F)orward, Turn (L)eft, Turn (R)ight,\n"
				+ "(G)rab the Gold, (S)hoot the Arrow, (C)limb out.\n"
				+ "(Q)uit the game, Use (X) to cheat.\n";
	
		public static string Victory = "!!!!!! You Win !!!!!!\n";

		public static string PitAdjacent = "A damp breeze is in the air!\n";

		public static string DragonAdjacent = "A foul stench is in the air!\n";

		public static string DragonStillAlive = "But there is still a dragon to slay.\n";

		public static string GoldLeftBehind = "But there is still gold to be found.\n";

		public static string InvalidCommand = "Nothing happens.\n";

		public static string Quit = "Quitter!!!\n";

		public static string FedDragon = "The Dragon Eats You !!!\n";

		public static string GoldRoom = "The room is glittering!\n";

		public static string Death = "You Die !!!\n";

		public static string Direction = "You are facing ";

		public static string Location = "You are in: ";

		public static string Bump = "You bump into a wall.\n";

		public static string NoArrow = "You don't have an arrow.\n";

		public static string Escape = "You escape the cave!!!";

		public static string PitFall = "You fall into a pit !!!";

		public static string GoldGet = "You got the gold !!!";

		public static string ArrowCheck = "You have 1 arrow that you can shoot.";

		public static string DragonKill = "You hear a giant roar in the distance!!!";

		public static string ArrowMiss = "You hear a thud in the distance.";

		public static string Move = "You walk into the next room.";

		public DCMessages ()
		{
		}
	}
}

