//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DragonCave
{
	public class DCPlayer
	{
		public string PlayerDirection = "EAST";
		public int PlayerRow;
		public int PlayerCol;
        public string CurrentDirection;
        

		public DCPlayer ()
		{
          

		}
		public void MoveForward()
		{
			if (PlayerDirection = "EAST" && PlayerCol < 3) {
				PlayerCol++;
				Console.WriteLine(DCMessages.Move);
			} else if (PlayerDirection = "WEST" && PlayerCol > 0) {
				PlayerCol--;
				Console.WriteLine(DCMessages.Move);
			} else if (PlayerDirection = "NORTH" && PlayerRow > 0) {
				PlayerRow--;
				Console.WriteLine(DCMessages.Move);
			} else if (PlayerDirection = "SOUTH" && PlayerRow < 3) {
				PlayerRow++;
				Console.WriteLine(DCMessages.Move);
			} else {
				Console.WriteLine (DCMessages.Bump);
			}
		}
		public void TurnLeft() {
			if (PlayerDirection == "EAST") {
				PlayerDirection = "NORTH"; 
				Console.WriteLine(DCMessages.Direction + "NORTH");
			}
			else if (PlayerDirection == "NORTH") {
				PlayerDirection = "WEST";
				Console.WriteLine(DCMessages.Direction + "WEST"); 
			}
			else if (PlayerDirection == "WEST") {
				PlayerDirection = "SOUTH";
				Console.WriteLine(DCMessages.Direction + "SOUTH"); 
			}
			else if (PlayerDirection == "SOUTH") {
				PlayerDirection = "EAST";
				Console.WriteLine(DCMessages.Direction + "EAST"); 
			}
			
		}
		
		public void TurnRight() {
			if (PlayerDirection == "EAST") {
				PlayerDirection = "SOUTH"; 
				Console.WriteLine(DCMessages.Direction + "SOUTH"); 
			}
			else if (PlayerDirection == "SOUTH") {
				PlayerDirection = "WEST";
				Console.WriteLine(DCMessages.Direction + "WEST"); 
			}
			else if (PlayerDirection == "WEST") {
				PlayerDirection = "NORTH";
				Console.WriteLine(DCMessages.Direction + "NORTH"); 
			}
			else if (PlayerDirection == "NORTH") {
				PlayerDirection = "EAST";
				Console.WriteLine(DCMessages.Direction + "EAST");; 
			}
			
		}

	}
}

