//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DragonCave
{
	public class DCRooms
	{
		public static string Pit = "P"; 
		public static string Dragon = "D";
		public static string Gold = "G";
		public static string Entrance = "E";

		public DCRooms ()
		{

		}
	}
}

